name: Build and Release v1.0

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8


      - name: Set Extensions Dir
        id: set_ext_dir
        run: |
          echo "Setting Extensions Dir..."
          mkdir ${HOME}/release
          mkdir /tmp/to
          echo "NEW_RELIC_EXTENSIONS_DIR=${HOME}/release" >> $GITHUB_ENV

      - name: Build with Gradle and verifyInstrumentation
        run: |
          ./gradlew build install verifyInstrumentation

      - name: Set release version
        id: set_release_version
        run: |
          major_version=2
          minor_version=0

          # Retrieve the latest release tag
          latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null) || true

          if [[ -n "$latest_tag" && $latest_tag == v* ]]; then
            # Extract the major and minor versions from the latest tag
            current_major_version=$(echo $latest_tag | cut -d'.' -f1 | sed 's/v//')
            current_minor_version=$(echo $latest_tag | cut -d'.' -f2)

            # Increment the minor version if it's less than 9
            if [[ $current_minor_version -lt 99 ]]; then
              minor_version=$((current_minor_version + 1))
              major_version=$((current_major_version))
            else
              # Increment the major version and reset the minor version to 0
              major_version=$((current_major_version + 1))
              minor_version=0
            fi
          fi

          # Set the release version environment variable
          release_version="v${major_version}.${minor_version}"
          echo "RELEASE_VERSION=${release_version}" >> $GITHUB_ENV

      - name: Set Tag
        id: set_tag
        run: echo "::set-output name=tag::${{ env.RELEASE_VERSION }}"

      - name: Set release name
        id: set_release_name
        run: |
          repo_name="${{ github.repository }}"
          sanitized_repo_name=$(echo "$repo_name" | awk -F 'newrelic-java-' '{print $2}')
          echo "RELEASE_NAME=${sanitized_repo_name}-instrumentation-" >> $GITHUB_ENV
          previous_tag=$(git describe --abbrev=0 --tags HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)

      - name: Create Archive
        run: |
          echo "CURRENT=${PWD}" >> $GITHUB_ENV
          cd ${HOME}/release
          zip -r /tmp/to/${{ env.RELEASE_NAME}}${{ steps.set_tag.outputs.tag }}.zip *.jar
          cd ${{env.CURRENT}}

      

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
                var changelog = ``;
                var tag = '' + `${{ steps.set_tag.outputs.tag }}`;
                const archivePath = '/tmp/to/${{ env.RELEASE_NAME}}${{ steps.set_tag.outputs.tag }}.zip';
                var response = await github.rest.repos.createRelease({
                  draft:false,
                  generate_release_notes:true,
                  name:tag,
                  owner:context.repo.owner,
                  prerelease:false,
                  repo:context.repo.repo,
                  tag_name:tag,
                  body:changelog
                });

                core.exportVariable('RELEASE_ID', response.data.id);
                core.exportVariable('RELEASE_URL', response.data.html_url);
                core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
              } catch (error) {
                core.setFailed(error.message);
              }
      - name: Upload Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: /tmp/to/${{ env.RELEASE_NAME}}${{ steps.set_tag.outputs.tag }}.zip
          asset_name: ${{ env.RELEASE_NAME}}${{ steps.set_tag.outputs.tag }}.zip
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_content_type: application/zip
     
     # github changelog
      - name: "Generate release changelog"
        id: github_changelog
        uses: Helmisek/conventional-changelog-generator@v1.0.6-release
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: "fix:Bug Fixes,feat:Features,doc:Documentation,build:Build Upgrades"
          template-path: ".github/workflows/CHANGELOG.tpl.md"
         
     
      - name: update CHANGELOG.md
        run: |
          # Content to add at the top
          # Get the current date in YYYY-MM-DD format
          release_date=$(date +"%Y-%m-%d")
          version="## Version: [${{env.RELEASE_VERSION}}](${{ env.RELEASE_URL }}) | Created: $release_date"
          content="$version${{steps.github_changelog.outputs.changelog}}"

          # Existing file
          file="CHANGELOG.md"

          # Create a temporary file with the content at the top and existing content below
          
          echo "$content" > temp_file.txt
          cat "$file" >> temp_file.txt

          # Overwrite the original file with the updated content
          mv temp_file.txt "$file"
          
          # Commit the updated CHANGELOG.md file
           git add CHANGELOG.md
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git commit -m "Update Changelog for Release [skip ci]"

          # Push the changes to the remote repository
           git push --quiet --set-upstream origin HEAD

      - name: Update Release Notes
        id: update_release
        run: |
          release_id="${{ env.RELEASE_ID }}"
          release_notes=${{steps.github_changelog.outputs.changelog}}
           # Remove leading and trailing spaces from release_notes using awk
          release_notes=$(echo "$release_notes" | awk '{$1=$1};1')
          # Escape double quotes in release_notes
          release_notes=$(echo "$release_notes" | sed 's/"/\\"/g')
          updated_release=$(curl -s -X PATCH -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                               -H "Accept: application/vnd.github.v3+json" \
                               -d "{\"body\": \"$release_notes\"}" \
                               "https://api.github.com/repos/${{ github.repository }}/releases/$release_id")
          echo "::set-output name=updated_release::$updated_release"     
