name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Build project
        run: ./gradlew build

      - name: Get branch name
        id: branch_name
        run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}

      - name: Get workflow run number
        id: workflow_run_number
        run: echo "::set-output name=run_number::${{ github.run_number }}"

      - name: Create tag
        id: create_tag
        run: echo "::set-output name=tag::v${{ steps.workflow_run_number.outputs.run_number }}"


      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWRELIC_BUILD_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ steps.create_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Publish release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NEWRELIC_BUILD_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./CHANGELOG.md
          asset_name: CHANGELOG.md
          asset_content_type: text/plain

      - name: Set release body
        run: echo "See the attached changelog for release details." > release_body.txt

      - name: Update release
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.NEWRELIC_BUILD_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('release_body.txt', 'utf8');
            github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ steps.create_release.outputs.release_id }},
              body: body
            });
