name: Changelog
on:
  release:
    types:
      - created
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: scottbrenner/generate-changelog-action@master
        with:
          token: ${{ secrets.NEWRELIC_BUILD_TOKEN }} 
